[FIREBASE_CERT]
type = "service_account"
project_id = "lqdchatventure"
private_key_id = "b92ccc8457562634d7311be8da7c594d3368277f"
private_key = """ -----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSgKckAqyKkLEM
EWPWGo+sU4GpWSDiauTepj2275NTXtJSTdkPgsorCYhVuDMF9zUXf5J0f1LN72/k
ETXHkTQeC9HuyCn745ZjNA/mmZpocRLMZzyQH7hi3NY8zDAFCfZXixuUljehlhIp
NcE9pwwCVf93bdHDgxnqR5FgD+ulP4+48Fffez+kynhn8Ylqeyv80djy+vPkfskz
9Lk+96oR13nK5y/H7dIY2tAjhdsmv1Nk42t/1I4M7IRR746pCsucUbQ9ezevgnJX
NQJJcGF16+sFTQtJGIkRpzgB+d1N+XhFbzG3cEtisLVVT5o906wC1EGKxhHglOiT
aO6XebxRAgMBAAECggEAHL+jTOU7b5uSKqCU+1ROAk6GwLEtS1EXpXtw29+qhO80
DZOaNzl+q7BcsRmK5a5LnFdb6YF8wc2tIs+fwpBDbmv6X8Wmu3e/MKtsPV/CFaGu
wy61C0E2QSw93ENjXvHEBgzVtjQ+KXbWDIEwcQVBTYoLrid+RMQKx1cQ941YPB5v
YapTvXj5xfysXeTL2cF4cgvArbNpyq3b0BfzZ876YHKM6Io8VQ8qHj60u/vISjGa
39P+nbgrlS162Egc4aIPRS8otCAD0m2IbN2wz9aDE/1Xfuxgt9dJnWdVU48POQGe
7qKgCUzNSuU0J7GYHzyxargna5HYDzagr0Aa7oVU+QKBgQDLDiRzNEVVDHFBt2/a
QwWVQDAvYwHv9tI5pcgfdHnKijmMzsCso7TAHw9y5ndPuAYSfQfem+GOwZFYe6RG
illnB8nLJyJjYFF11sNNXwb/hvaz1cSg4rm1MF0OgVZvY8MAQCxH3u4OSTYoBLlQ
iF2/auUBexCoufdp8+s+EFDYHQKBgQC4s6P2v1I808I9ed8eIOnx4DCAskxzfUCf
ANjRGCq49B2TRGfyD7MzDR3YQ2L1z2ikp9Kp2WnMt2oFRi0UyaBOOx/5WELVmCtY
jwNTKsfq2zFhqNynlhhAiui1SLHx8xLyrPo+Vn8aBXktcKP8ovEea3QR1dtWwbLO
UZpzMgHGxQKBgFbCaiyXLvCR6mpr2GznqiEFVhFJOnCvg0+CWCmoeMljmgdh581b
/UUBgHZVprD3LhEEPzKMZCm85z9pRN2nC2AMYdpdlEHly6iP5M7QRYs0vYBFXEhp
13NlgL1L4gSiGZWn1cO3qvuLqIocyplwSq4ZHFQvowSUwPQSdncEPaa5AoGBAIQR
R0NvCBGgZPpqQ0Saykz+PhA37XyC6gsHowDX4+x9+QvNVPn7ieoODfIONRuIo81g
hryWThVobLG6vQ9pIGvv0OwM1TU/ancXQ4xbQbnH46ZuBOD77PlxmfXONhbH9Rt6
3jBmztk/YqdALLG/nONgeA0sunptZDoslWCbODP1AoGATTF6liLMoRT82JHS7pWC
8tEY7cpfqy5RXlUOmpA2MGaGt30FnJdE+48WTyks0AtJ787RW3MCl+SY5CqAfeuJ
dOpR8DiPclqZ0B9K6VytzN2msA2tvBAUJYUVJ/dZqVw4RC5Ti7fl5XNr/3JZoM5d
czp6fbfasEpFe6tpHrEuXqs=
-----END PRIVATE KEY----- """
client_email = "firebase-adminsdk-p777u@lqdchatventure.iam.gserviceaccount.com"
client_id = "112523989763138824653"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs" 
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-p777u%40lqdchatventure.iam.gserviceaccount.com"